### ISSUE TITLE
Update deprecated test class base 'LightPlatformCodeInsightFixtureTestCase'

### ISSUE THREAD

**Issue by wejrox** [intuit/DockDockBuild#17]
All test files other than `MakefileParserTest` currently extend an outdated base class `LightPlatformCodeInsightFixtureTestCase` where they should be extending `BasePlatformTestCase`.

**Comment by piyalibanerj** [comment]
Updated the deprecated class 'LightPlatformCodeInsightFixtureTestCase' to 'BasePlatformTestCase' in all test files. PR #18.
