### ISSUE TITLE
Update usage of deprecated Gradle features

### ISSUE THREAD

**Issue by HilaG** [intuit/DockDockBuild#20]
**Is this a bug report, or a feature request?**
Feature request

**What is the current behavior?**
https://travis-ci.com/github/intuit/DockDockBuild/builds/188064511#L653

**What is the expected behavior?**
Update deprecated Gradle features to make it compatible w/ Gradle 7

**Comment by wejrox** [comment]
On it!

**Comment by HilaG** [comment]
Hi @wejrox ,
I'm still getting 'Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.'
https://travis-ci.com/github/intuit/DockDockBuild/jobs/394956916#L398

I took a look at https://scans.gradle.com/s/jr3yq6mulyx2q and it shows that the problem is 
'Copying or archiving duplicate paths with the default duplicates strategy has been deprecated.'

So I'm merging but keeping the issue open.

Thanks!

**Comment by wejrox** [comment]
All good, I can't seem to pin down where that's occurring unfortunately!
