### ISSUE TITLE
Find an alternative for using com.intellij.modules.java

### ISSUE THREAD

**Issue by HilaG** [intuit/DockDockBuild#3]
Find an alternative for depending on com.intellij.modules.java during the build in resources/META-INF/plugin.xml file.
com.intellij.modules.java isn't supported by PyCharm, GoLand and more so if this will change, the plugin will support a lot more IntelliJ IDEs

**Comment by dotbg** [comment]
Note. The PR is for the plugin.xml changes only. 

Further changes may be required, see the [Plugins Targeting IntelliJ Platform-Based IDEs](https://jetbrains.org/intellij/sdk/docs/products/dev_alternate_products.html) page.
