### ISSUE TITLE
Fix usage of API scheduled for removal - SimpleDataContext.getSimpleContext

### ISSUE THREAD

**Issue by HilaG** [intuit/DockDockBuild#37]
Deprecated method SimpleDataContext.getSimpleContext(...) is invoked in DockDockBuildRunTargetAction.actionPerformed(...). 
This method will be removed in IntelliJ 2022.1 so this needs to change to another function

**Comment by tekgal** [comment]
I would like to pick this up if it is not claimed.

**Comment by HilaG** [comment]
Looking into the [usage statistics](https://plugins.jetbrains.com/docs/marketplace/product-versions-in-use-statistics.html) it's safe to upgrade to 2020.2 / 2020.3 but 2021 looks too new

**Comment by upuneetu** [comment]
@HilaG could you help me understand how I could get the version number of the release in which a particular commit went through? I believe the following would be the one that we need.
https://github.com/JetBrains/intellij-community/commit/16d9064c76a6d6f12e10f3fb6df731ce737d76ed

**Comment by HilaG** [comment]
We can always try to built it w/ the new code and see what's the minimum version it works w/

**Comment by upuneetu** [comment]
I'm confused as to what to do here. I know what function to use, but since we can't build it now successfully it doesn't make sense to raise a PR. @HilaG any suggestions? I tried changing the idea-version in the plugin.xml file (to "211.4961.30" since in the commit "idea/211.4961.30" was mentioned. Even then the build is failing with the same error as before. (Error: "...None of the following functions can be called with the arguments supplied: ..."

**Comment by HilaG** [comment]
@upuneetu Maybe the version needs to be changed in the build.gradle file to get the correct version. Do you have the changes in your fork? I can take a look to see what's happening

**Comment by upuneetu** [comment]
@HilaG I was able to fix the build issues with the above PR. Upgraded the java version 11 as I got the following error after making the required idea version & intellij changes:
`> Task :compileJava FAILED
/Users/pu001/Repo/hacktober/DockDockBuild/src/main/java/name/kropp/intellij/makefile/psi/impl/MakefilePrerequisiteMixin.java:6: error: cannot access FileReferenceSet
import com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReferenceSet;
                                                                    ^
  bad class file: /Users/pu001/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2021.2.2/aa03fa700ac9c82d03acad5eadd5e547b5ccc008/ideaIC-2021.2.2/lib/platform-impl.jar(com/intellij/psi/impl/source/resolve/reference/impl/providers/FileReferenceSet.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.`
