### ISSUE TITLE
GH actions fails

### ISSUE THREAD

**Issue by HilaG** [intuit/DockDockBuild#59]
**Is this a bug report, or a feature request?**
bug

**What is the current behavior?**
GH actions fails in build stage

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a PR and see that the CI fails

**What is the expected behavior?**
CI pass

**Please provide all relevant details.**
https://scans.gradle.com/s/3ygnvr427qg6c/console-log?anchor=411&page=1

**Comment by shaharkozi** [comment]
Fixed: https://github.com/intuit/DockDockBuild/pull/66
