### ISSUE TITLE
Update deprecated API usage AnnotationHolder.createWeakWarningAnnotation

### ISSUE THREAD

**Issue by HilaG** [intuit/DockDockBuild#6]
Update deprecated method AnnotationHolder.createWeakWarningAnnotation(...) which is invoked in MakefileAnnotator.annotate(...)

**Comment by wejrox** [comment]
I'd like to be assigned to this issue! And please don't forget to add `hacktoberfest` to the topic on the repository!

**Comment by HilaG** [comment]
Thank you for your code contribution!
I've added the `hacktoberfest` tag :)
