### ISSUE TITLE
Update deprecated API usage IconLoader.getIcon

### ISSUE THREAD

**Issue by HilaG** [intuit/DockDockBuild#8]
Update deprecated method IconLoader.getIcon(String) which is invoked in MakefileFileTypeKt.<clinit>()

**Comment by wejrox** [comment]
According to https://github.com/joewalnes/idea-community/blob/master/platform/util/src/com/intellij/openapi/util/IconLoader.java#L69 IconLoader.getIcon(String) is not deprecated, IconLoader.getIcon(Image) is. Am I missing something here?

**Comment by HilaG** [comment]
Hi,
It is deprecated based on the IntelliJ plugins verification results I get and here:
https://github.com/joewalnes/idea-community/blob/1fa2c45953ed08667da52b1b83d44c56eb83b043/platform/util/src/com/intellij/openapi/util/IconLoader.java#L69

**Comment by HilaG** [comment]
Oh, [that repo](https://github.com/joewalnes/idea-community/blob/master/platform/util/src/com/intellij/openapi/util/IconLoader.java#L69) looks way old - the last commit was almost 10 years ago.

<img width="1006" alt="Screen Shot 2020-10-04 at 21 42 06" src="https://user-images.githubusercontent.com/11246352/95024249-7c900980-068a-11eb-805d-0ecf7dda5c06.png">

**Comment by wejrox** [comment]
Very strange, the source documentation was automatically downloaded for me when I opened the repository within IDEA Ultimate 2020.2.2 but it didn't mention any sort of deprecation either, perhaps there's a difference within the documentation available between the build of IntelliJ I'm running (IU-202.7319.50) and that which you've got output from (IU-203.4203.26)? Looks like someone is on it though!

**Comment by dotbg** [comment]
@wejrox  yes. I have noticed, the deprecation is done in current master, not on 2020.2. 
The PR is very small, though
